version: '3'

networks:
  server_network:

services:
  # Website
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    # gunicorn -c gunicorn_config.py server.wsgi:application --timeout 10800
    depends_on:
      - database
    networks:
      - server_network
  # Database
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgress
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - server_network
